plugins {
    id "org.jetbrains.kotlin.multiplatform"
    id "org.jetbrains.kotlin.plugin.compose"
    id "com.android.kotlin.multiplatform.library"
    id "io.github.archivesteak.compose"
}

kotlin {
    targetHierarchy.default()

    android {
        namespace = "com.google.samples.apps.diceroller.shared"
        compileSdk = 37
    }

    jvm()

    sourceSets {
        getByName("commonMain") {
            dependencies {
                implementation("io.github.archivesteak.compose.ui:ui:COMPOSE_VERSION_PLACEHOLDER")
                implementation("io.github.archivesteak.compose.runtime:runtime:COMPOSE_VERSION_PLACEHOLDER")
                implementation("io.github.archivesteak.compose.foundation:foundation:COMPOSE_VERSION_PLACEHOLDER")
                implementation("io.github.archivesteak.compose.material3:material3:COMPOSE_MATERIAL3_VERSION_PLACEHOLDER")
            }
        }
    }
}
