plugins {
    id 'org.jetbrains.kotlin.multiplatform'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'io.github.archivesteak.compose'
}

kotlin {
    jvm('desktop') {}

    sourceSets {
        commonMain.dependencies {
            api "io.github.archivesteak.compose.runtime:runtime:COMPOSE_VERSION_PLACEHOLDER"
            api "io.github.archivesteak.compose.foundation:foundation:COMPOSE_VERSION_PLACEHOLDER"
            api "io.github.archivesteak.compose.material:material:COMPOSE_VERSION_PLACEHOLDER"
            api "io.github.archivesteak.compose.ui:ui-tooling:COMPOSE_VERSION_PLACEHOLDER"
        }
        desktopMain.dependencies {
            implementation compose.desktop.currentOs
        }
    }
}
