plugins {
    id "org.jetbrains.kotlin.multiplatform"
    id "io.github.archivesteak.compose"
    id "org.jetbrains.kotlin.plugin.compose"
}

kotlin {
    js(IR) {
        browser()
    }
    jvm {}

    sourceSets {
        named("commonMain") {
        }
        named("jsMain") { 
            dependencies {
                implementation("io.github.archivesteak.compose.runtime:runtime:COMPOSE_VERSION_PLACEHOLDER")
            }
        }
        named("jvmMain") {
            dependencies {
                implementation(compose.desktop.currentOs)
            }
        }
    }
}
