plugins {
    id "org.jetbrains.kotlin.multiplatform"
    id "org.jetbrains.kotlin.plugin.compose"
    id "io.github.archivesteak.compose"
}

kotlin {
    js { browser() }

    sourceSets {
        commonMain.dependencies {
            api("io.github.archivesteak.compose.runtime:runtime:COMPOSE_VERSION_PLACEHOLDER")
            api("io.github.archivesteak.compose.ui:ui:COMPOSE_VERSION_PLACEHOLDER")
            api("io.github.archivesteak.compose.foundation:foundation:COMPOSE_VERSION_PLACEHOLDER")
        }

        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation("io.github.archivesteak.compose.ui:ui-test:COMPOSE_VERSION_PLACEHOLDER")
        }
    }
}
